export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE'

export const GET_ALL_DATA_REQUEST = 'GET_ALL_DATA_REQUEST'
export const GET_ALL_DATA_SUCCESS = 'GET_ALL_DATA_SUCCESS'
export const GET_ALL_DATA_FAILURE = 'GET_ALL_DATA_FAILURE'

export const SWITCH_DARK_MODE = 'SWITCH_DARK_MODE'